export interface Woning {
  id: string;
  naam: string;
  collectie: "the shore" | "the fields";
  locatie: string;
  prijs: number;
  slaapkamers: number;
  badkamers: number;
  maxGasten: number;
  oppervlakte: string | null;
  tags: string[];
  slogan: string;
  introductie: string;
  beschrijving: string;
  volledigeBeschrijving: string;
  buurt?: string;
  hoogtepunten: string[];
  inCheckin: string;
  uitCheckin: string;
  heroFoto: string;
  fotos: string[];
  boekUrl: string;
}

export const woningen: Woning[] = [
  {
    id: "nosso-knokke",
    naam: "Nosso Logies",
    collectie: "the shore",
    locatie: "Heist-aan-Zee, Knokke",
    prijs: 370,
    slaapkamers: 2,
    badkamers: 2,
    maxGasten: 6,
    oppervlakte: "110m²",
    tags: ["Strand op 2 min", "Privé koer", "2 badkamers"],
    slogan: "Goed slapen, goed eten, goed ademen. Twee minuten van de zee.",
    introductie:
      "Sommige plekken voel je meteen. Nosso is er één van. Niet omdat het opschept - maar omdat het klopt. Het licht, de ruimte, de stilte van het koertje op een zaterdagochtend. Dit is geen Airbnb-gok. Dit is een woning die we persoonlijk hebben geïnspecteerd, ingericht en klaargemaakt voor mensen die weten wat ze willen.",
    beschrijving:
      "Op twee minuten van de Noordzee, verscholen in een rustige straat in Heist-aan-Zee. Een lichtrijk appartement van 110m² met twee slaapkamers, twee volledige badkamers en een privé koer.",
    volledigeBeschrijving:
      "Nosso Logies is gebouwd rond één idee: ruimte om te ademen. De open leefruimte baadt de hele dag in natuurlijk licht en loopt naadloos over in een volledig uitgeruste keuken: oven, vaatwasser, inductiekookplaat, microgolf, koffiemachine, waterkoker, broodrooster en alles wat je nodig hebt voor een echte maaltijd. De eettafel biedt ruimte voor het hele gezelschap. De eerste slaapkamer heeft een kwalitatief tweepersoonsbed. De tweede heeft een tweepersoonsbed én een stapelbed, ideaal voor gezinnen met kinderen. Twee volledige badkamers betekent nooit wachten - elk voorzien van kwaliteitshanddoeken, shampoo, douchegel en haardroger. De woonkamer heeft een smart-tv, gezelschapsspellen en snelle wifi. Stap buiten op het privé koertje: beschut, groen en rustig van jou. Ochtendkoffie, een aperitief bij zonsondergang, een glas wijn nadat de kinderen slapen.",
    buurt:
      "Nosso Logies ligt in Heist-aan-Zee, het ontspannen westelijke uiteinde van Knokke-Heist. Het strand ligt op twee minuten te voet: twaalf kilometer breed, goudkleurig zand dat zich uitstrekt van de vissershaven in Heist tot de exclusieve strandclubs van Het Zoute. De beroemde Lippenslaan en Kustlaan van Knokke zijn omzoomd met boetiekjes, kunstgalerijen en zonnige terrassen - op een korte tram- of fietsrit afstand. Het Zwinnatuurpark, een uniek getijdenreservaat op de Belgisch-Nederlandse grens, is een prachtige bestemming voor vogelspotters en rustige wandelingen. Fietsen door de polders richting Cadzand, Damme of Brugge is een van de mooiste ritten aan de kust. Met de wagen ben je op 20 minuten in Brugge.",
    hoogtepunten: [
      "110m² - ruimte om te ademen",
      "Strand op 2 minuten te voet",
      "Privé koertje - jouw stille oase",
      "2 volledige badkamers - nooit wachten",
      "Volledig uitgeruste keuken",
      "Zelf inchecken via slim slot",
    ],
    inCheckin: "15:00",
    uitCheckin: "10:00",
    heroFoto: "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-132.jpg",
    fotos: [
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-132.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-4.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-7.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-11.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-12.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-17.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-21.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-29.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-35.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-40.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-53.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-59.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-60.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-62.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-67.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-68.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-81.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-96.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-108.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-109.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-114.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-115.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-123.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-124.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-127.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-176.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-189.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-195.jpg",
      "/images/woningen/knokke-new/2026-AmelieBauwens-Moroww-V2-2 kopie.jpg",
    ],
    boekUrl:
      "https://book.moroww.com/nl/properties/698c63ff3d9a2d0013fefd72?minOccupancy=1",
  },
  {
    id: "ann-helena-ursel",
    naam: "Chalet Ann-Helena",
    collectie: "the fields",
    locatie: "Ursel, Meetjesland",
    prijs: 220,
    slaapkamers: 2,
    badkamers: 1,
    maxGasten: 5,
    oppervlakte: null,
    tags: ["Bosrand", "Privétuin met vijver", "Gezinsvriendelijk"],
    slogan: "Tussen Gent en Brugge. Maar eigenlijk ergens heel anders.",
    introductie:
      "Er bestaat een moment waarop het bos begint te werken. Vijf minuten na aankomst laat je de snelweg los. Tien minuten later begint iedereen zachter te praten. Chalet Ann-Helena is gebouwd voor dat moment. Warm hout, hoge plafonds, een vijver die nergens naartoe hoeft. Dit is hoe ontsnappen aanvoelt als je het goed doet.",
    beschrijving:
      "Een warme houten chalet in het hart van het grootste bos van Oost-Vlaanderen. Hoge plafonds, natuurlijk hout, een privétuin met vijver en stilte als standaard.",
    volledigeBeschrijving:
      "Chalet Ann-Helena is een authentieke houten chalet met twee verdiepingen, waar natuurlijk hout, warm licht en het omliggende bos samen een onmiddellijk gevoel van rust creëren. De open leefruimte draait om een lichte woonkamer met grote ramen die uitkijken op de tuin. Nestel je in de ruime leren hoeksalon met een plaid en een kaars, of kom samen aan de eettafel voor lange, ongehaaste maaltijden. De volledig uitgeruste keuken heeft alles: oven, vaatwasser, Nespresso-machine, waterkoker, broodrooster en meer. Op de eerste verdieping wachten twee comfortabele slaapkamers. De masterbedroom met tweepersoonsbed en verse lakens, de tweede slaapkamer afgestemd op kinderen: stapelbed, extra eenpersoonsbed en reisbedje op aanvraag. De badkamer heeft een bad, douche en verwarmde handdoekenrek. Buiten nodigt een ruim privéterras uit tot buiten eten, terwijl de sfeervol vijver en de volledig omheinde tuin kinderen de vrijheid geven om veilig te spelen. Gratis parkeren voor 2 wagens op het terrein.",
    buurt:
      "Chalet Ann-Helena ligt in het hart van het Drongengoedbos in Ursel - een charmant dorp in de Meetjeslandse regio. Met 750 hectare is dit het grootste aaneengesloten bos van Oost-Vlaanderen: een landschap van eeuwenoude drevenstructuren, paarse heide, knuppelpaden en stille waterwegen. Meer dan 236 kilometer bewegwijzerde wandelpaden starten pal aan de voordeur. Kinderen zijn dol op het Kabouter Wandelpad en de natuurspeelplaatsen. De Maldegemse Veldhoek is een verborgen parel - heide en knuppelpaden die aanvoelen als een miniatuur Hoge Venen. In het dorp: Villa Maria voor een heerlijk diner, Bar Boudoir voor ontspannen koffie, Brasserie Het Jagershof aan de bosrand. Gent op 30 minuten, Brugge op 25 minuten. Opgelet: de chalet is bereikbaar via een onverhard bospad - rijd voorzichtig bij nat weer.",
    hoogtepunten: [
      "Hart van het Drongengoedbos",
      "Privétuin met vijver - volledig omheind",
      "Gezinsvriendelijk - stapelbed, reisbedje, speelgoed",
      "Gratis parkeren voor 2 wagens",
      "Terras en balkon met bosuitkijk",
      "Gent (30 min) en Brugge (25 min)",
    ],
    inCheckin: "17:00",
    uitCheckin: "10:00",
    heroFoto: "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-64.jpg",
    fotos: [
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-64.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-2.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-3.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-4.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-5.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-6.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-7.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-8.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-9.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-10.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-11.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-12.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-13.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-14.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-15.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-16.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-17.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-18.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-19.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-20.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-21.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-22.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-23.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-24.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-25.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-26.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-27.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-28.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-29.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-30.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-31.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-32.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-33.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-34.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-35.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-36.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-37.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-38.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-39.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-40.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-41.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-42.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-43.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-44.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-45.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-46.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-47.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-48.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-49.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-50.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-51.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-52.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-53.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-54.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-55.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-56.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-57.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-58.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-59.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-60.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-61.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-62.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-63.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-65.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-66.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-67.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-68.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-69.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-70.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-71.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-72.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-73.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-74.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-75.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-76.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel-77.jpg",
      "/images/woningen/ursel-new/Bogaertstraat 17 Ursel.jpg",
    ],
    boekUrl:
      "https://book.moroww.com/nl/properties/696b49bf47f69b0013026516?minOccupancy=1",
  },
  {
    id: "moroww-oostende",
    naam: "Oostende",
    collectie: "the shore",
    locatie: "Oostende",
    prijs: 210,
    slaapkamers: 2,
    badkamers: 2,
    maxGasten: 4,
    oppervlakte: null,
    tags: ["16e verdieping", "Zeezicht", "Privé parking"],
    slogan: "Hoog boven de kust. Helemaal voor jullie.",
    introductie:
      "Er is zeezicht. En dan is er dit. Zestien verdiepingen boven de drukte, met de Noordzee voor je neus en de golfers onder je. Geen gedeelde gang. Geen toevallige buren. Gewoon een appartement dat je het gevoel geeft dat Oostende van jou is - en een parkeerplaats die er echt bij hoort.",
    beschrijving:
      "Zestien verdiepingen hoog, met de Noordzee voor je en de Golf van Oostende aan je zij. Ensuite badkamers, panoramisch balkon en privé ondergrondse parking.",
    volledigeBeschrijving:
      "16e verdieping. De Noordzee voor je, de Golf van Oostende naast je, en de stad uitgespreid aan je voeten. De open leefruimte baadt de hele dag in natuurlijk licht, met een comfortabele salon, eethoek en een volledig uitgeruste keuken: vaatwasser, oven, koffiemachine en alles wat je verwacht. Stap op het privébalkon en laat het uitzicht de rest doen: zonsopgang boven de golfbaan, zonsondergang boven de zee. Elke slaapkamer is een privéretraite met eigen ensuite badkamer: inloopdouche of bad, kwaliteitsarmaturen en hotelwaardige voorzieningen. En dan is er nog de parking. Een privé ondergrondse plaats, inbegrepen - een echte zeldzaamheid in Oostende.",
    buurt:
      "Oostende is veel meer dan alleen strand: het is een levendige kuststad met musea, fijne restaurants, markten en boetieks. Dankzij de hoge ligging geniet je hier van unieke 360-graden zichten over zee, golf en stad. Of je nu houdt van cultuur, gastronomie of lange wandelingen langs de kust: alles ligt binnen handbereik. De Kusttram brengt je vlot naar alle badplaatsen en stopt voor de deur: van Knokke tot De Panne. Brugge bereik je in slechts 15 minuten met de trein.",
    hoogtepunten: [
      "16e verdieping - panoramisch zeezicht",
      "Ensuite badkamer in elke slaapkamer",
      "Privé ondergrondse parking inbegrepen",
      "Panoramisch balkon",
      "Rookvrij pand",
      "Kusttram voor de deur",
    ],
    inCheckin: "17:00",
    uitCheckin: "10:00",
    heroFoto:
      "/images/woningen/oostende-new/6e71ca30-bb8f-11f0-96ff-dd8382026135 kopie.jpg",
    fotos: [
      "/images/woningen/oostende-new/6e71ca30-bb8f-11f0-96ff-dd8382026135 kopie.jpg",
      "/images/woningen/oostende-new/6ed4b090-bb8f-11f0-b593-b7fa59eda9ac kopie.jpg",
      "/images/woningen/oostende-new/6f3e8280-bb8f-11f0-9df9-133c9daab682 kopie.jpg",
      "/images/woningen/oostende-new/6f79d4b0-bb8f-11f0-b879-599fa8385b5e kopie.jpg",
      "/images/woningen/oostende-new/6ffe6340-bb8f-11f0-81e2-97c8d345614a kopie.jpg",
      "/images/woningen/oostende-new/70a4dba0-bb8f-11f0-b9a0-3325af39a98d kopie.jpg",
      "/images/woningen/oostende-new/70ffdb90-bb8f-11f0-a90c-3b5b633348f0 kopie.jpg",
      "/images/woningen/oostende-new/71dd8490-bb8f-11f0-84c1-7f4982eb7516 kopie.jpg",
      "/images/woningen/oostende-new/72c36b20-bb8f-11f0-a453-2ba9b187f403 kopie.jpg",
      "/images/woningen/oostende-new/73b55e20-bb8f-11f0-9b40-efe250da0764 kopie.jpg",
      "/images/woningen/oostende-new/73df46f0-bb8f-11f0-98f2-593cb5634d65 kopie.jpg",
      "/images/woningen/oostende-new/74b5ea50-bb8f-11f0-806d-11c84929dee4 kopie.jpg",
      "/images/woningen/oostende-new/7640bd00-bb8f-11f0-b7ea-d9a1599a120e kopie.jpg",
      "/images/woningen/oostende-new/76a4bcf0-bb8f-11f0-a903-9bb57552af8d kopie.jpg",
      "/images/woningen/oostende-new/76d0bdf0-bb8f-11f0-9659-5b18a83d5fba kopie.jpg",
      "/images/woningen/oostende-new/77af3a80-bb8f-11f0-af23-2d4a83235607 kopie.jpg",
      "/images/woningen/oostende-new/78a76bb0-bb8f-11f0-b5dc-89e4377b09bc kopie.jpg",
      "/images/woningen/oostende-new/79ac93a0-bb8f-11f0-8bc5-659d879ac298 kopie.jpg",
      "/images/woningen/oostende-new/7a1e5ef0-bb8f-11f0-8e02-a5dc325183e4 kopie.jpg",
      "/images/woningen/oostende-new/7ab84070-bb8f-11f0-bcce-731e46b96e9d kopie.jpg",
      "/images/woningen/oostende-new/7af2b8a0-bb8f-11f0-a3be-93967557ddca kopie.jpg",
      "/images/woningen/oostende-new/7b2abb20-bb8f-11f0-937d-a538b705f9da kopie.jpg",
      "/images/woningen/oostende-new/7b939f30-bb8f-11f0-a132-bb0ab281860f kopie.jpg",
      "/images/woningen/oostende-new/7bcaa0a0-bb8f-11f0-986e-2173804c94f8 kopie.jpg",
      "/images/woningen/oostende-new/7bfa4300-bb8f-11f0-9542-3f96c9361152 kopie.jpg",
      "/images/woningen/oostende-new/7ca394b0-bb8f-11f0-bb53-5f8c9e3fee8e kopie.jpg",
      "/images/woningen/oostende-new/7cd24bd0-bb8f-11f0-a48b-cd298ada06b4 kopie.jpg",
      "/images/woningen/oostende-new/7d7c1ad0-bb8f-11f0-bfcf-d3b5274c33c6 kopie.jpg",
      "/images/woningen/oostende-new/7dcb6240-bb8f-11f0-9ad0-9bcd69b0f19a kopie.jpg",
      "/images/woningen/oostende-new/7e137780-bb8f-11f0-8c99-0f32b66097ed kopie.jpg",
      "/images/woningen/oostende-new/7e555070-bb8f-11f0-a651-4d0627bd5d38 kopie.jpg",
    ],
    boekUrl:
      "https://book.moroww.com/nl/properties/695140859e91eb0014db3eb1?minOccupancy=1",
  },
  {
    id: "cozy-relax-beernem",
    naam: "The Cozy Relax Home",
    collectie: "the fields",
    locatie: "Beernem",
    prijs: 600,
    slaapkamers: 4,
    badkamers: 2,
    maxGasten: 10,
    oppervlakte: null,
    tags: ["Zwembad", "Hottub", "Tuin met BBQ"],
    slogan: "Groot genoeg voor het hele gezelschap. Rustig genoeg voor de rest.",
    introductie:
      "Voor groepen die echt samen willen zijn. Niet op elkaars lip - maar wel samen. Vier slaapkamers, een zwembad, een hottub, een vuurschaal en een tuin die groot genoeg is om iedereen hun eigen hoekje te geven. Beernem is geen bestemming die je kent. Dat is precies waarom het zo goed werkt.",
    beschrijving:
      "Stijlvolle vakantiewoning voor maximaal 10 gasten, midden in het groen in Beernem. Luxueuze badkamers, ruime tuin met overdekt terras, zwembad, vuurschaal en petanquebaan.",
    volledigeBeschrijving:
      "Binnen vind je vier gezellige slaapkamers met kwalitatieve boxspringbedden en een mezzanine met twee eenpersoonsbedden. Er zijn twee moderne badkamers: één met inloopdouche en één met ligbad, plus een apart gastentoilet. De open leefruimte bestaat uit een lichtrijke zithoek, een grote eettafel en een volledig uitgeruste keuken: vaatwasser, oven, koelkast met diepvries, microgolfoven, koffiemachine en wasmachine. Buiten wacht de absolute troef van deze woning. Ontspan in de hottub, steek de vuurschaal aan, neem een duik in het zwembad of speel een potje pétanque terwijl de kinderen zich uitleven op de trampoline of speeltuin. Het overdekte terras is de ideale plek om te genieten, ongeacht het weer. Het buitenzwembad is niet verwarmd - ideaal tijdens de warmere maanden of voor wie houdt van een frisse duik. De hottub, BBQ en vuurschaal zijn het hele jaar beschikbaar.",
    buurt:
      "Beernem ligt in een groene, rustige omgeving tussen Brugge en Gent - de ideale uitvalsbasis voor wie houdt van natuur, fietsen en wandelen. In de buurt vind je mooie bossen, landelijke wegen en charmante dorpjes. Brugge bereik je op 14 km, de kust op 25 km en Gent op 35 km. Tegelijk bereik je vlot culturele hotspots, restaurants en winkels in de omliggende steden. De woning is bereikbaar met de wagen en heeft private parkeergelegenheid voor 5 wagens op het terrein.",
    hoogtepunten: [
      "Zwembad, hottub en vuurschaal",
      "Overdekt terras met BBQ en petanquebaan",
      "Tot 10 gasten - ideaal voor groepen",
      "14 km van Brugge, 25 km van de kust",
      "Parkeren voor 5 wagens op het terrein",
      "4 slaapkamers met boxspringbedden",
    ],
    inCheckin: "15:00",
    uitCheckin: "11:00",
    heroFoto:
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.42.01.jpeg",
    fotos: [
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.42.01.jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.41.11.jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.41.33.jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.43.55.jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.45.31.jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.47.24.jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.47.53.jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.48.52.jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.51.51.jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.52.50.jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.55.29.jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.55.29 (1).jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.55.29 (2).jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.55.56 (1).jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 15.01.30.jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 15.01.42.jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 15.04.58.jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 15.05.29.jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 15.11.03.jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 15.11.03 (1).jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 15.11.03 (2).jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.18.18.jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.18.18 (1).jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.18.18 (4).jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.18.19 (1).jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.18.19 (2).jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.18.19 (3).jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.18.19 (4).jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.18.19 (5).jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.18.19 (6).jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.18.19 (7).jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.18.19 (8).jpeg",
      "/images/woningen/beernem-new/WhatsApp Image 2025-11-02 at 14.18.19 (9).jpeg",
    ],
    boekUrl:
      "https://book.moroww.com/nl/properties/690781db69d1700012bf6dd3?minOccupancy=1",
  },
];

export const BADGE_STYLES: Record<Woning["collectie"], { bg: string; color: string }> = {
  "the shore": { bg: "#EEBC9D", color: "#1A1A1A" },
  "the fields": { bg: "#CBD085", color: "#1A1A1A" },
};
